### ISSUE TITLE
pathogen-repo-build: Cancel AWS Batch job when GitHub run is cancelled

### ISSUE THREAD

**Issue by victorlin** [nextstrain/.github#108]
### Context

Currently, canceling a GitHub run will only detach the job. [Example](https://github.com/nextstrain/ncov/actions/runs/11133100504/job/30938460896#step:5:2851):

```
Detaching from job, as requested
```

### Description

It would be nice if canceling a job on GitHub also cancels the corresponding AWS job. This would better allow us to use GitHub runs as an indicator for and primary interface to what's happening on AWS Batch.

### Possible solution

The current step is [Attach to AWS Batch job](https://github.com/nextstrain/.github/blob/654db5566b2a5cdeb1c072092363c69646f38465/.github/workflows/pathogen-repo-build.yaml#L402C15-L402C38) so it does not make sense to cancel in this step. Instead, a new step can be added to cancel the batch job AWS Batch job on [`cancelled()`](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/evaluate-expressions-in-workflows-and-actions#cancelled).

**Comment by victorlin** [comment]
I should get my eyes checked...

https://github.com/nextstrain/.github/blob/654db5566b2a5cdeb1c072092363c69646f38465/.github/workflows/pathogen-repo-build.yaml#L668

**Comment by tsibley** [comment]
👀
