### ISSUE TITLE
Prevent scheduled workflow from being automatically disabled

### ISSUE THREAD

**Issue by joverlee521** [nextstrain/.github#112]
## Context

The GitHub [workflow docs](https://docs.github.com/en/actions/managing-workflow-runs/disabling-and-enabling-a-workflow) state:

> In a public repository, scheduled workflows are automatically disabled when no repository activity has occurred in 60 days.

## List of affected workflows

- [status CI](https://github.com/nextstrain/status/actions/workflows/ci.yaml): manually re-enabled on 2024-09-10
- [Update GitHub project](https://github.com/nextstrain/project-board/actions/workflows/update_github_project.yml): disabled on 2023-02-07 ([previous issue](https://github.com/nextstrain/project-board/issues/5))
- [dengue ingest-to-phylo workflow](https://github.com/nextstrain/dengue/actions/workflows/ingest-to-phylogenetic.yaml): manually re-enabled on [2024-09-26](https://github.com/nextstrain/.github/issues/112#issuecomment-2444526999)
- [rabies ingest-to-phylo workflow](https://github.com/nextstrain/rabies/actions/workflows/ingest-to-phylogenetic.yaml): manually re-enabled on 2024-10-29
- rsv [fetch-and-ingest](https://github.com/nextstrain/rsv/actions/workflows/fetch-and-ingest.yaml) and [rebuild](https://github.com/nextstrain/rsv/actions/workflows/rebuild.yaml) workflows: manually re-enabled on 2024-11-04
- zika [fetch-and-ingest](https://github.com/nextstrain/zika/actions/workflows/ingest-to-phylogenetic.yaml): manually re-enabled on 2024-11-25

## Possible solution

1. Keep manually re-enabling affected workflows as they are noticed to be disabled
2. Use the [Keepalive Workflow action](https://github.com/marketplace/actions/keepalive-workflow) on affected workflows
3. Create our own workflow that runs some activity as the Nextstrain bot. I'm not entirely sure what counts as "repository activity" but a couple options:
    - Push dummy commit to main
    - Push dummy commit to a long term "keep-alive" branch
    - Create and delete a new branch
    - Create and close a new issue
    - Other ideas?
4. [Make a central keep-alive workflow that uses the GitHub REST API to disable/enable affected workflows every <60 days](https://github.com/nextstrain/.github/issues/112#issuecomment-2444527037)
5. ⛔️ Use Terraform run regularly to control this. The official GitHub provider for Terraform doesn't expose the endpoint we need.

**Comment by victorlin** [comment]
Thanks for transferring @joverlee521, I dropped the ball on this one. Probably not going to do this over the next few weeks so if anyone wants to take it, feel free.

**Comment by joverlee521** [comment]
I had to manually re-enable another workflow today, so I decided to pick this up -> https://github.com/nextstrain/.github/pull/118.
