### ISSUE TITLE
docs-ci: Check external links

### ISSUE THREAD

**Issue by tsibley** [nextstrain/.github#29]
Running Sphinx's `linkcheck` builder to systematically check our external links would be really helpful to catch broken links resulting from anything from typos when authoring to third-party site reorganizations.

It would have caught a bunch of external link errors in https://github.com/nextstrain/docs.nextstrain.org/pull/139, for example. (Not calling out that PR specifically! This sort of error is very common and easy to make. But that PR made me wonder why we weren't already running `linkcheck`.)

A second job (for parallelism) or just a subsequent step in the current job should run something like:

    SPHINXOPTS="-W --keep-going" make linkcheck

which will produce a bunch of messages to stdout/stderr output but also `build/linkcheck/output.{txt,json}`. Both of the latter files (and probably just the whole `build/` dir!) should be uploaded as a workflow artifact. [Examples of output](https://gist.github.com/tsibley/40f3a57a2e68f578a7dff51692bc9cc3) from https://github.com/nextstrain/docs.nextstrain.org/commit/6fcf76f.

Since `linkcheck` will exit with a non-zero status on errors, it'll fail the CI job. I believe this is what we want.

[Some configuration](https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-the-linkcheck-builder) for `linkcheck` is usually required to ignore links that are actually ok, and this would fall on each doc project to configure itself.

## related issues:
- [x] nextstrain/docs.nextstrain.org#14

**Comment by genehack** [comment]
@tsibley is this still something that needs to be done?

**Comment by tsibley** [comment]
I think it's (still) worth doing. Clearly not high priority, but fairly low effort to actually do.
