### ISSUE TITLE
Centralize existing pathogen build workflows

### ISSUE THREAD

**Issue by joverlee521** [nextstrain/.github#46]
### Context
We now have a [centralized reusable GitHub Action workflow for running pathogen builds](https://github.com/nextstrain/.github/blob/261c64f084a721aa5779bc796c38e07d12f31e81/.github/workflows/pathogen-repo-build.yaml). 

We should update existing pathogen build workflows to use the centralized workflow to make future maintenance easier for ourselves and to discover any pitfalls in reusable workflow that may have been overlooked during development. 

Hopefully there shouldn't be any huge changes that need to happen to the reusable workflow, but better to discover them now than later when it's widely used. 

### Description
Here's a list of repos that should be updated to use the new workflow: 

- [x] monkeypox (https://github.com/nextstrain/monkeypox/pull/190) 
- [x] https://github.com/nextstrain/ncov-ingest/pull/440
- [ ] [ncov](https://github.com/nextstrain/ncov/tree/master/.github/workflows)
- [x] rsv (updated as part of https://github.com/nextstrain/rsv/pull/37)
- [x] [seasonal-flu](https://github.com/nextstrain/seasonal-flu/tree/master/.github/workflows)
- [x] forecasts-ncov (https://github.com/nextstrain/forecasts-ncov/pull/60 + https://github.com/nextstrain/forecasts-ncov/pull/62)

### Examples
See example use of the reusable workflow in [seasonal-flu](https://github.com/nextstrain/seasonal-flu/blob/a0a9f1054c5385a908502cefee4670dcd5ca837e/.github/workflows/run-public-builds.yaml)

**Comment by genehack** [comment]
@joverlee521 looks like the only unticked box in the original TODO list is for `ncov`, and I see a merged PR against `ncov` ...is this issue maybe done?

**Comment by joverlee521** [comment]
@genehack The merged PR is for `ncov-ingest` which is a separate repo than `ncov`. The `ncov` GH Action workflows still need to be migrated.

**Comment by genehack** [comment]
The need to update the CI workflow in `ncov` has been moved to a [new issue in the `ncov` repo](https://github.com/nextstrain/ncov/issues/1109). 

Closing this issue out.

**Comment by joverlee521** [comment]
@genehack, I completely misread your previous issue! This is actually regarding the use of the `pathogen-repo-build` workflow. I've made a new issue to track the separate task: https://github.com/nextstrain/ncov/issues/1113
