### ISSUE TITLE
ENH(pathogen-repo-ci): Cache "setup-nextstrain" to save 1-2min (>50%)

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/.github#56]
### Context
When looking at runtime of `pathogen-repo-ci` workflows, 1min (docker) to 2min (conda) are spent setting up the runtime, while actual builds take often less than 1 minute.

### Description
It should be possible to save actions runtime by caching the result of "setup-nextstrain".

**Comment by genehack** [comment]
We discussed this in the Nextstrain dev chat meeting today (20240529) and the general consensus was the value of having potential issues surface from consistent re-building outweighed any potential advantage of time savings. Closing this ticket out.
