### ISSUE TITLE
Triage and tag open issues across repositories

### ISSUE THREAD

**Issue by sidneymbell** [nextstrain/.github#6]
From @jameshadfield :  
>@huddlej has proposed we systematically go through all the repos and use the following labels, which I think is a great idea. We are aware this won't be possible over night, and won't prevent us adding issues to the project boards.
Priority: low / moderate / high
Difficulty: easy / moderate / difficult
Type: bug / enhancement / duplicate
Avaiability: Needs triage / good first issue / help wanted
Components affected: docs / narratives / frontend / backend / scientific-builds
Status: accepted / do-not-merge / breaking / blocking / needs review

**Comment by huddlej** [comment]
I've created these labels for nextstrain.org, auspice, augur, and ncov, so I'm closing this now. Not all of the above labels have proven to be helpful, so I have omitted them (e.g., do-not-merge, scientific-builds) for now.

To standardized these further, we should set these as [default labels for the nextstrain organization](https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/managing-default-labels-for-repositories-in-your-organization). This will allow new repositories to start with these labels.

This change will require help from someone with permissions to edit nextstrain's org settings.
