### ISSUE TITLE
ENH: Allow pathogen-repo-ci to invoke workflow in subfolder

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/.github#63]
### Context
Current pathogen-repo-ci seems to assume that we don't need to customize workdir in nextstrain build ., i.e. we can't set nextstrain build foobar.

Our nextstrain/pathogen-repo-template, however, puts the main workflow in a folder. So we should add that feature.

See https://bedfordlab.slack.com/archives/C01LCTT7JNN/p1695664810319929 for discussion
### Description
A clear and concise description of what you want to happen

### Possible solution
Tried in #57 but introduce a bug in upload-artifact.
Tried to address in #62 but couldn't get it to work.

### Checklist

- [ ] Reenable monkeypox again for augur CI once this is resolved (disabled in https://github.com/nextstrain/augur/pull/1324)

**Comment by victorlin** [comment]
[zika](https://github.com/nextstrain/zika) no longer has a top-level workflow, increasing the need for this. I'll make PRs to disable it from all CI for now.

**Comment by joverlee521** [comment]
This has been superceded by https://github.com/nextstrain/.github/pull/90
