### ISSUE TITLE
Allow pathogen-repo-ci to use a local version of Augur 

### ISSUE THREAD

**Issue by joverlee521** [nextstrain/.github#66]
The [augur CI workflow is currently _not_ using the pathogen-repo-ci](https://github.com/nextstrain/augur/blob/7cb384877cb61e26781dec947f81fee29462c008/.github/workflows/ci.yaml#L74-L76) because it wants to test from-source install of Augur. It would be nice for it to use the centralized CI workflow so that we don't have to maintain both. 

Consider adding an input to pathogen-repo-ci to point to a ref in Augur to check-out a copy of Augur. 
Then we could use the nextstrain CLI `--augur` option to point to the local copy of Augur. It does not do an actual `pip install` so it wouldn't pull in any new dependencies. 

However, I think we can work around that for now with:
```
nextstrain build --exec bash --augur ./augur . <<< 'python -m pip install ../augur && snakemake ...'
```

**Comment by tsibley** [comment]
> Then we could use the nextstrain CLI `--augur` option to point to the local copy of Augur. It does not do an actual `pip install` so it wouldn't pull in any new dependencies. However, I think we can work around that for now with: …

Hmm. My first instinct is to recommend against this. I think that `--augur` (and related options) are likely to be removed from Nextstrain CLI in the future. (There was some brief discussion of this… somewhere.) The two big caveats with `--augur` (and co.) are:

1. Dep changes aren't actually handled (as you noted)
2. Only works with locally containerized runtimes (Docker, Singularity)

I don't see either of those being worthwhile to fix given the effort:reward… so the example workaround above would be ~permanent.

But maybe given our dev requirements here we'd want to reconsider the Augur overlay feature given this concrete use case?

**Comment by genehack** [comment]
We discussed this in the Nextstrain dev chat meeting today (20240529) and the consensus was that the partial duplication of the CI logic in the Augur test suite was better than having to add support for "ambient" environment runtimes to the `pathogen-repo-ci` action (as well as potentially dealing with the future removal of the command options @tsibley mentions above). 

Closing issue.
