### ISSUE TITLE
Output AWS Batch job ID from pathogen-repo-build worklfow

### ISSUE THREAD

**Issue by joverlee521** [nextstrain/.github#79]
If downstream jobs/workflows require the AWS Batch job ID of the build, we need to add an output to the pathogen-repo-build workflow. This idea was prompted by https://github.com/nextstrain/seasonal-flu/issues/159. I'm not able to think of any other use case that would require the AWS Batch job ID output...

I don't think it's too much work to add/maintain the output but will revisit this another time.

**Comment by jameshadfield** [comment]
This seems very similar to https://github.com/nextstrain/zika/pull/52 where we added a job to the workflow as a workaround because we couldn't pass information from one job to another. But [artifacts](https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts#passing-data-between-jobs-in-a-workflow) (for files) or [outputs](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idoutputs) (for strings) should let us do this, right?

**Comment by joverlee521** [comment]
Ah, this is a technical bit in the GitHub Action workflow. Now that I'm looking at it again, we already store the AWS Batch job ID as an output from the `run-build` job. 

https://github.com/nextstrain/.github/blob/d15f4f99addc57acc8ccaf102a01e8a31bd46c6d/.github/workflows/pathogen-repo-build.yaml.in#L281-L282

We just need to make it an [output of the reusable workflow](https://docs.github.com/en/actions/using-workflows/reusing-workflows#using-outputs-from-a-reusable-workflow).

**Comment by jameshadfield** [comment]
Right, and its value is obtained by [parsing the build output](https://github.com/nextstrain/.github/blob/d15f4f99addc57acc8ccaf102a01e8a31bd46c6d/.github/workflows/pathogen-repo-build.yaml.in#L259C11-L259C140):

```
echo "AWS_BATCH_JOB_ID=$(sed -nE 's/.+AWS Batch Job ID\:.+ ([-a-f0-9]+)$/\1/p' < "$NEXTSTRAIN_BUILD_LOG")" | tee -a "$GITHUB_ENV"
```

This approach is what I'm suggesting we aim for with regards to surfacing relevant information from the reusable workflow. In other words, we design some structured text pattern which (ingest/pathogen) workflows can print and the reusable workflow will parse this from the logs and surface via an output. For instance, we could use this to know whether there were "new data"  or "no new data" in an ingest.

**Comment by tsibley** [comment]
> In other words, we design some structured text pattern which (ingest/pathogen) workflows can print and the reusable workflow will parse this from the logs and surface via an output.

Why not produce a file instead of pattern matching on log output?

**Comment by jameshadfield** [comment]
> Why not produce a file instead of pattern matching on log output?

👍  I should have said "design some structure" -- a file would be just fine.
