### ISSUE TITLE
Standardize pathogen-repo-ci use across pathogen repos

### ISSUE THREAD

**Issue by joverlee521** [nextstrain/.github#84]
Ideas here came out of discussion with @tsibley in our 1:1 regarding https://github.com/nextstrain/.github/pull/62#issuecomment-2105402378. This would supersede #63 + #62. 

## Proposal

With the standardization of pathogen repos following the pathogen-repo-guide, we can now enforce the standardized use of the `pathogen-repo-ci` workflow. 

In order to use the centralized `pathogen-repo-ci`, a pathogen repo will need to meet two requirements. 

1. follow a strict repo organization (currently required to have a `phylogenetic` subdirectory)
2. use a standard mechanism for specifying the CI build, e.g. use a standard CI config that can be specified with 
    
    ```
    nextstrain build phylogenetic --configfiles build-configs/ci/config.yaml
    ````

This would simplify each pathogen repo's CI workflow to:
```yaml
name: CI

on:
  - push
  - pull_request

jobs:
  ci:
    uses: nextstrain/.github/.github/workflows/pathogen-repo-ci.yaml@master
```

Then the docker-base/conda-base CIs can be simplified to just matrix of pathogen repos instead of needing to [pass in additional build args](https://github.com/nextstrain/docker-base/blob/822a45939508929beeb3e664680f7e0d5475c549/.github/workflows/ci.yml#L214-L220).  

### Concrete steps 

- [x] https://github.com/nextstrain/.github/issues/93
- [x] https://github.com/nextstrain/.github/issues/89
- [x] https://github.com/nextstrain/.github/issues/94
- [x] https://github.com/nextstrain/docker-base/pull/223
- [x] https://github.com/nextstrain/conda-base/pull/85
- [x] https://github.com/nextstrain/augur/pull/1549

**Comment by victorlin** [comment]
I'm a bit out of the loop here. What's the difference between mpox's CI (which [uses](https://github.com/nextstrain/mpox/blob/7f5adc3cab0c3034e455882581cc081f26f5ebbe/.github/workflows/ci.yaml#L17) `pathogen-repo-build`) and avian-flu's CI (which [uses](https://github.com/nextstrain/avian-flu/blob/297ded669a519dd0d3eee9399088a4bc22287cd1/.github/workflows/ci.yaml#L9) `pathogen-repo-ci`)? Can avian-flu use `pathogen-repo-build`? Or is mpox's use of `pathogen-repo-build` considered temporary and will be replaced during the 3rd task here?

**Comment by joverlee521** [comment]
> Or is mpox's use of pathogen-repo-build considered temporary and will be replaced during the 3rd task here?

Yup, the use of the `pathogen-repo-build` in CI is considered a temporary change (if ~6 months is considered temporary 😅). The plan would be to switch all pathogen GitHub Action CI workflows back to `pathogen-repo-ci`.

**Comment by genehack** [comment]
Related/precursor work: https://github.com/nextstrain/.github/issues/89
