### ISSUE TITLE
Should the pathogen-repo-ci be louder if no workflows are run? 

### ISSUE THREAD

**Issue by joverlee521** [nextstrain/.github#92]
### TODO

- [x] move `nextstrain-pathogen.yaml` file checks out into a single step prior to workflow run steps
- [x] add aggregate success step, modeled on [`pathogen-repo-build` `wait-conclusion` logic](https://github.com/nextstrain/.github/blob/7f910e6c7d3d475500b063e4861a26b63c168cb8/.github/workflows/pathogen-repo-build.yaml#L596-L613) to trigger failure when no build steps are run

### Original issue content

Follow up to #89 

Just noticed in our [docker-base CI workflow](https://github.com/nextstrain/docker-base/actions/runs/9440522488) that all the pathogen-repo-ci jobs have "succeeded" even though none of them ran any workflows. 

This outcome is pretty misleading and can potentially lead to us missing when changes actually break pathogen workflows if we don't notice that the workflows never actually ran within CI.

**Comment by joverlee521** [comment]
I think fine to leave each ingest/phylogenetic/nextclade workflow as optional, but maybe we should have a final conclusion job that checks at least _one_ of the workflows ran?

**Comment by genehack** [comment]
> I think fine to leave each ingest/phylogenetic/nextclade workflow as optional, but maybe we should have a final conclusion job that checks at least _one_ of the workflows ran?

In this _particular_ case, every repo where the `pathogen-repo-ci` workflow is being used lacks the `nextstrain-pathogen.yaml` file in the repo root. 

Maybe instead of testing for the presence of that file in the individual build steps, and skipping if it's absent, there should be a preliminary job that checks once, and generates a failure (e.g., `exit 1` or the like) if the file is missing.

**Comment by joverlee521** [comment]
> In this _particular_ case, every repo where the `pathogen-repo-ci` workflow is being used lacks the `nextstrain-pathogen.yaml` file in the repo root.
> 
> Maybe instead of testing for the presence of that file in the individual build steps, and skipping if it's absent, there should be a preliminary job that checks once, and generates a failure (e.g., `exit 1` or the like) if the file is missing.

Yup, definitely support erroring early on this! In addition, I still think it'd be helpful to fail when _none_ of the expected workflows ran.

**Comment by genehack** [comment]
> Yup, definitely support erroring early on this! In addition, I still think it'd be helpful to fail when _none_ of the expected workflows ran.

You wouldn't happen to be able to point me to an example of that sort of aggregated failure check in a GitHub Action, would you?

**Comment by joverlee521** [comment]
> You wouldn't happen to be able to point me to an example of that sort of aggregated failure check in a GitHub Action, would you?

I think the `wait-conclusion` job in the pathogen-repo-build workflow is a good example:

https://github.com/nextstrain/.github/blob/7f910e6c7d3d475500b063e4861a26b63c168cb8/.github/workflows/pathogen-repo-build.yaml#L596-L613

**Comment by genehack** [comment]
> > You wouldn't happen to be able to point me to an example of that sort of aggregated failure check in a GitHub Action, would you?
> 
> I think the `wait-conclusion` job in the pathogen-repo-build workflow is a good example:

Ah, yeah, cool, I can do the couple changes here.

**Comment by joverlee521** [comment]
Resolved by a combination of #95, #96, #98, and #99.
