### ISSUE TITLE
Pin existing uses of `pathogen-repo-ci`

### ISSUE THREAD

**Issue by joverlee521** [nextstrain/.github#93]
See #84 for context 

Update the existing use of the `pathogen-repo-ci` across Nextstrain repos to pin them to ~https://github.com/nextstrain/.github/commit/ef5c51a9a3a22bde9243a090bbada0cd3a983f73 (since we have not tagged a specific version)~ `v0` so that they continue to run as expected without having to conform the folder structure required by https://github.com/nextstrain/.github/pull/90. 

Searched for `pathogen-repo-ci` with https://github.com/search?q=org%3Anextstrain+%2Fpathogen-repo-ci%5B.%5Dyaml%40%2F&type=code: 

- [x] avian flu -> https://github.com/nextstrain/avian-flu/pull/59
- [x] conda-base -> updated as part of https://github.com/nextstrain/conda-base/pull/70
- [x] docker-base -> https://github.com/nextstrain/docker-base/pull/217
- [x] ebola -> https://github.com/nextstrain/ebola/pull/8
- [x] lassa -> https://github.com/nextstrain/lassa/pull/5
- [x] mumps -> https://github.com/nextstrain/mumps/pull/8
- [x] ncov -> https://github.com/nextstrain/ncov/pull/1115
- [x] rsv -> https://github.com/nextstrain/rsv/pull/64
- [x] rsv-old -> not updating since it's an archived repo
- [x] seasonal-flu -> https://github.com/nextstrain/seasonal-flu/pull/170
- [x] tb -> https://github.com/nextstrain/tb/pull/11

**Comment by genehack** [comment]
\<suggestion type="gentle">
Maybe instead of pinning to https://github.com/nextstrain/.github/commit/ef5c51a9a3a22bde9243a090bbada0cd3a983f73, add a `v0` tag to https://github.com/nextstrain/.github/commit/ef5c51a9a3a22bde9243a090bbada0cd3a983f73 and then pin to that? 
\</suggestion>

**Comment by joverlee521** [comment]
> <suggestion type="gentle"> Maybe instead of pinning to [ef5c51a](https://github.com/nextstrain/.github/commit/ef5c51a9a3a22bde9243a090bbada0cd3a983f73), add a `v0` tag to [ef5c51a](https://github.com/nextstrain/.github/commit/ef5c51a9a3a22bde9243a090bbada0cd3a983f73) and then pin to that? </suggestion>

Didn't actually get to this today, since I got distracted by ncov-ingest, will do tomorrow. 

Also noting that the commit hash `ef5c51a9a3a22bde9243a090bbada0cd3a983f73` was copied over from the old issue. There's since been other updates in the repo _before_ the pathogen-repo-ci update, so the `v0` tag should be at baf4c033695f6d58dfa27a0febf750ce5fbb1817

**Comment by joverlee521** [comment]
[Search query](https://github.com/search?q=org%3Anextstrain+%2Fpathogen-repo-ci%5B.%5Dyaml%40master%2F+AND+NOT+repo%3Anextstrain%2Frsv-old&type=code) for `pathogen-repo-ci@master` only returns `.github` and `seasonal-cov` repos now 🎉
